# Generated by Django 4.1.3 on 2022-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_id", models.IntegerField(blank=True, null=True)),
                ("text", models.CharField(blank=True, max_length=45, null=True)),
                ("username", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "Comments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("picture", models.ImageField(upload_to="images")),
            ],
            options={
                "db_table": "Photos",
                "managed": False,
            },
        ),
    ]
